# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-09 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageUpload',
        ),
        migrations.AlterField(
            model_name='image',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
