# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-09 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20190309_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img_url',
            new_name='image',
        ),
    ]
